themeapp/urls.py
from django.urls import path
from .views import *


app_name = "themeapp"
urlpatterns = [
	path("", HomeView.as_view(),name="home"),
    path("about_us/",AboutView.as_view(),name="about"),
    path("contact_us/",ContactView.as_view(),name="contact"),
    path("gallery/",GalleryView.as_view(),name="gallery"),


    path('my-admin/', AdminHomeView.as_view(), name="adminhome"),
    path("my-admin/food/list/", AdminFoodListView.as_view(), name="adminfoodlist"),
    path("my-admin/food/create/", AdminFoodCreateView.as_view(), name="adminfoodcreate"),
    
    path("my-admin/food/<int:pk>/update/", AdminFoodUpdateView.as_view(), name="adminfoodupdate"),
    path("my-admin/food/<int:pk>/delete/", AdminFoodDeleteView.as_view(), name="adminfooddelete"),

    path("login/",LoginView.as_view(),name="login"),
    path("logout/",LogoutView.as_view(),name="logout"),
]

themeproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("themeapp.urls")),
    
]
urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

themeapp/models.py
from django.db import models
from django.core.validators import validate_email


class Food(models.Model):
	name=models.CharField(max_length=200)
	image=models.ImageField(upload_to="foods")
	description=models.TextField()
	price=models.DecimalField(max_digits=19,decimal_places=2)

	def __str__(self):
		return self.name

class Slider(models.Model):
	title=models.CharField(max_length=200)
	image=models.ImageField(upload_to="Slider")

	def __str__(self):
	  return self.title

class Testimonial(models.Model):
    name=models.CharField(max_length=200)
    image=models.ImageField(upload_to="Testimonial")
    organization=models.CharField(max_length=200)
    review=models.TextField()

    def __str__(self):
    	return self.name

class Gallery(models.Model):
    image=models.ImageField(upload_to="galleries")
    caption=models.CharField(max_length=500)

    def __str__(self):
       return self.caption 


class Subscriber(models.Model):
	name=models.CharField(max_length=500)
	email_address=models.EmailField(unique="TRUE",validators=[validate_email])

	def __str__(self):
		return self.caption


























# Create your models here.

themeapp/forms.py
from django import forms
from .models import *


class FoodForm(forms.ModelForm):
	class Meta:
		model = Food
		fields = ['name', 'image', 'description', 'price']
		widgets = {
			'name': forms.TextInput(attrs={
				'class': 'form-control mb-3',
				'placeholder': 'Enter food name...'
				}),
			'image': forms.ClearableFileInput(attrs={
				'class': 'form-control mb-3'
				}),
			'description': forms.Textarea(attrs={
				'class': 'form-control mb-3',
				'placeholder': 'Enter description...'
				}),
			'price': forms.NumberInput(attrs={
				'class': 'form-control mb-3',
				'placeholder':'Enter Price of the food..'
				})
		}

class LoginForm(forms.Form):
    username =forms.CharField(widget=forms.TextInput())
    password=forms.CharField(widget=forms.PasswordInput())		

themeapp/views.py
from django.shortcuts import render,redirect 
from django.views.generic import *
from .models import *
from .forms import *
from django.contrib.auth import authenticate,login,logout



class HomeView(TemplateView):
	template_name = "home.html"

	def get_context_data(self,**kwargs):
		context=super().get_context_data(**kwargs)
		context["myfoods"]=Food.objects.all().order_by("-id")
		context["alltestimonial"]=Testimonial.objects.all()
		context["myslider"]=Slider.objects.all()
		context["thegallery"]=Gallery.objects.all()




		return context

class AboutView(TemplateView):
	template_name="about.html"

class ContactView(TemplateView):
	 template_name="contact.html"


class GalleryView(TemplateView):
	template_name="gallery.html"

class AdminRequiredMixin(object):
	def dispatch(self,request,*args,**kwargs):
		if request.user.is_authenticated:
			pass
		else:
			return redirect("/login/")	

		return super().dispatch(request,*args,**kwargs)	


class AdminHomeView(AdminRequiredMixin,TemplateView):
	template_name = "admintemplates/adminhome.html"
 
				
class AdminFoodListView(AdminRequiredMixin,ListView):
	template_name = "admintemplates/adminfoodlist.html"
	queryset = Food.objects.all()
	context_object_name = "ourfoodlist"


class AdminFoodCreateView(AdminRequiredMixin,CreateView):
	template_name = "admintemplates/adminfoodcreate.html"
	form_class = FoodForm
	success_url = "/my-admin/food/list/"


class AdminFoodUpdateView(AdminRequiredMixin,UpdateView):
	template_name = "admintemplates/adminfoodcreate.html"
	form_class = FoodForm
	model = Food
	success_url = "/my-admin/food/list/"

class AdminFoodDeleteView(AdminRequiredMixin,DeleteView):
	template_name = "admintemplates/adminfooddelete.html"
	model = Food
	success_url = "/my-admin/food/list/"

class LoginView(FormView):
	template_name ="login.html"
	form_class =LoginForm
	success_url ="/my-admin/food/list/"

	def form_valid(self,form):
		a=form.cleaned_data["username"]
		b=form.cleaned_data["password"]
		user=authenticate(username=a,password=b)
		if user is not None:
			login(self.request,user)
		else:
			return render(self.request,"login.html",{"error":"invalid username or password", 'form': form})
			


		return super().form_valid(form)
class LogoutView(View):
	def get(self,request):
		logout(request)
		return redirect("/")

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block abc %} main-banner-2{% endblock %}
{% block aboutpage %}active{% endblock %}




{% block body %}
	<div class="breadcrumb-w3ls py-1">
		<div class="container">
			<ol class="breadcrumb m-0">
				<li class="breadcrumb-item">
					<a href="index.html">Home</a>
				</li>
				<li class="breadcrumb-item active" aria-current="page">About Us</li>
			</ol>
		</div>
	</div>
	<!-- //page details -->

	<!-- about  -->
	<section class="about-inner py-5">
		<div class="container pt-xl-5 pt-lg-3">
			<h3 class="title-w3 mb-5 font-weight-bold">About Us <span>Something about us</span></h3>
			<div class="row">
				<div class="col-lg-6 w3lsits_works-grid mt-xl-4">
					<div class="wthree-bottom">
						<h6 class="subheading-w3ls text-uppercase text-dark mb-4">DEAL OF THE <span class="font-weight-bold">DAY</span>
							organic good <span class="font-weight-bold">foods 50%</span> off</h6>
						<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, eaque ipsa
							quae ab illo inventore veritatis et quasi architecto.</p>
						<a href="about.html" class="btn button-style mt-sm-5 mt-4">Read More</a>
					</div>
				</div>
				<div class="col-lg-6 w3lsits_works-grid1 mt-lg-0 mt-sm-5 mt-4">
					<img src="{% static 'images/about.jpg' %}" alt="" class="img-fluid" />
				</div>
			</div>
		</div>
	</section>
	<!-- //about -->

	<!-- middle -->
	<section class="what-w3ls">
		<div class="container-fluid py-xl-5 py-lg-3">
			<div class="offset-xl-7 offset-lg-6 offset-md-4 offset-sm-2">
				<div class="grids-whtas pr-xl-5">
					<h3 class="tittle text-wh mb-5 font-weight-bold">763+ fruits, vegetables & lot more</h3>
					<p class="lead text-li">Fresh From Our Farm ut leo cursus rhoncus. Nullam dui mi, vulputate ac metus at,
						semper varius orci. Nulla accumsan ac elit in congue.</p>
					<hr class="my-4">
					<p class="text-li">Rerum hic tenetur a sapiente delectus reiciendis maiores alias consequatur aut consequat
						sapien ut leo cursus
						rhoncus.Nullam dui mi, vulputate ac metus.</p>
					<a href="about.html" class="btn button-style mt-sm-5 mt-4">Read More</a>
				</div>
			</div>
		</div>
	</section>
	<!-- //middle -->

	<!-- team -->
	<section class="team pb-5" id="farmer">
		<div class="container pb-xl-5 pb-lg-3">
			<h3 class="title-w3 mb-5 font-weight-bold">Our Farmers <span>Caption Here</span></h3>
			<div class="row inner-sec-w3layouts-w3pvt-lauinfo">
				<div class="col-md-4 team-grids text-center">
					<img src="{% static 'images/team1.jpg' %}" class="img-fluid" alt="">
					<div class="team-info">
						<div class="caption mb-3">
							<h4>John Doe</h4>
						</div>
						<div class="social-icons-section">
							<a class="fac" href="#">
								<i class="fa fa-facebook"></i>
							</a>
							<a class="twitter mx-2" href="#">
								<i class="fa fa-twitter"></i>
							</a>
							<a class="google" href="#">
								<i class="fa fa-google-plus"></i>
							</a>
						</div>
					</div>
				</div>
				<div class="col-md-4 team-grids my-md-0 my-4 text-center">
					<img src="{% static 'images/team3.jpg' %}" class="img-fluid" alt="">
					<div class="team-info">
						<div class="caption mb-3">
							<h4>Adam Ster</h4>
						</div>
						<div class="social-icons-section">
							<a class="fac" href="#">
								<i class="fa fa-facebook"></i>
							</a>
							<a class="twitter mx-2" href="#">
								<i class="fa fa-twitter"></i>
							</a>
							<a class="google" href="#">
								<i class="fa fa-google-plus"></i>
							</a>
						</div>
					</div>
				</div>
				<div class="col-md-4 team-grids text-center">
					<img src="{% static 'images/team2.jpg' %}" class="img-fluid" alt="">
					<div class="team-info">
						<div class="caption mb-3">
							<h4>Chris Tina</h4>
						</div>
						<div class="social-icons-section">
							<a class="fac" href="#">
								<i class="fa fa-facebook"></i>
							</a>
							<a class="twitter mx-2" href="#">
								<i class="fa fa-twitter"></i>
							</a>
							<a class="google" href="#">
								<i class="fa fa-google-plus"></i>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- team -->

	<!-- testimonials -->
	<div class="testimonials py-5" id="testi">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="title-w3 mb-5 text-wh font-weight-bold">What Our Customers Say
				<span>Excellent Reviews for our Website</span>
			</h3>
			<div class="carousel-inner">
				<div class="row">
					<div class="col-lg-6 w3_testimonials_grid">
						<div class="bg-wh p-sm-5 p-4">
							<p class="sub-test-w3ls">Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil
								impedit quo minus id quod possimus, omnis voluptas.
							</p>
							<div class="row mt-5">
								<div class="col-3 testi-img-res">
									<img src="{% static 'images/te1.jpg' %}" alt=" " class="img-fluid" />
								</div>
								<div class="col-9 w3_testi_grid mt-xl-3 mt-lg-2 mt-md-4 mt-2">
									<h5 class="mb-2">Thomas Carl</h5>
									<p>Sed do eiusmod</p>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-6 w3_testimonials_grid mt-lg-0 mt-4">
						<div class="bg-wh p-sm-5 p-4">
							<p class="sub-test-w3ls">Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil
								impedit quo minus id quod possimus, omnis voluptas.
							</p>
							<div class="row mt-5">
								<div class="col-3 testi-img-res">
									<img src="{% static 'images/te2.jpg' %}" alt=" " class="img-fluid" />
								</div>
								<div class="col-9 w3_testi_grid  mt-xl-3 mt-lg-2 mt-md-4 mt-2">
									<h5 class="mb-2">Adam Ster</h5>
									<p>Sed do eiusmod</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- //testimonials -->
{% endblock %}

templates/admintemplates/adminfoodcreate.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}


{% block body %}



            <!-- main-heading -->
            <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2>
            <!--// main-heading -->

            <!-- Tables content -->
            <section class="tables-section">
                

               
                

                <!-- table7 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Food Form</h4>
                    <div class="table-responsive">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form.as_p}}
                            <button class="btn btn-info w-100">Save Data</button>
                        </form>
                    </div>
                </div>
                <!--// table7 -->

            </section>
{% endblock %}

templates/admintemplates/adminfooddelete.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}


{% block body %}


            <!-- Tables content -->
            <section class="tables-section">
                
                <!-- table7 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Delete Food</h4>
                    <div class="table-responsive">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <button class="btn btn-danger">Delete</button>
                        </form>
                    </div>
                </div>
                <!--// table7 -->

            </section>
{% endblock %}

templates/admintemplates/adminfoodlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}


{% block body %}



            <!-- main-heading -->
            <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2>
            <!--// main-heading -->

            <!-- Tables content -->
            <section class="tables-section">
                

               
                

                <!-- table7 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Responsive Table</h4>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Food name</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Image</th>
                                    <th scope="col">Action</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                            	{% for food in ourfoodlist %}
                                <tr>
                                    <th scope="row">{{forloop.counter}}</th>
                                    <td>{{food.name}}</td>
                                    <td>{{food.price}}</td>
                                    <td><img src="{{food.image.url}}" width="100"></td>
                                    <td>
                                    	<a href="{% url 'themeapp:adminfoodupdate' food.id %}" class="btn btn-primary">Update</a>
                                    	<a href="{% url 'themeapp:adminfooddelete' food.id %}" class="btn btn-danger">Delete</a>
                                    </td>
                                    
                                </tr>
                               	{% endfor %}
                                
                            </tbody>
                        </table>
                    </div>
                </div>
                <!--// table7 -->

            </section>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
	<title>Organic Food Agriculture Category Bootstrap Responsive Web Template | Home :: W3layouts</title>
	<!-- Meta tag Keywords -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8" />
	<meta name="keywords" content="Organic Food Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!-- //Meta tag Keywords -->

	<!-- Custom-Files -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Bootstrap-Core-CSS -->
	<link href="{% static 'css/css_slider.css' %}" type="text/css" rel="stylesheet" media="all">
	<!-- banner slider -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
	<!-- Style-CSS -->
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
	<!-- Font-Awesome-Icons-CSS -->
	<!-- //Custom-Files -->

	<!-- Web-Fonts -->
	<link href="//fonts.googleapis.com/css?family=Poiret+One&amp;subset=cyrillic,latin-ext" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Mada:200,300,400,500,600,700,900&amp;subset=arabic" rel="stylesheet">
	<!-- //Web-Fonts -->
</head>

<body>
	<!-- main banner -->
	<div class="{% block abc %}{% endblock %}" id="home">
		<!-- header -->
		<header>
			<div class="container-fluid">
				<div class="header d-md-flex justify-content-between align-items-center py-sm-4 py-3 px-xl-5 px-lg-3 px-2">
					<!-- logo -->
					<div id="logo">
						<h1><a class="" href="index.html">Bishal</a></h1>
					</div>
					<!-- //logo -->
					<!-- nav -->
					<div class="nav_w3ls">
						<nav>
							<label for="drop" class="toggle toogle-2">Menu</label>
							<input type="checkbox" id="drop" />
							<ul class="menu">
								<li class="{% block homepage %}{% endblock %}"><a href="{% url 'themeapp:home' %}">Home</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2 {% block aboutpage %}{% endblock %}"><a href="{% url 'themeapp:about' %}">About Us</a></li>
								<li class="{% block gallerypage %}{% endblock %}"><a href="{% url 'themeapp:gallery' %}">Gallery</a></li>
								<li class="mx-lg-4 mx-md-3 my-md-0 my-2">
									<!-- First Tier Drop Down -->
									<label for="drop-2" class="toggle">Dropdown <span class="fa fa-angle-down" aria-hidden="true"></span>
									</label>
									<a href="#">Dropdown <span class="fa fa-angle-down" aria-hidden="true"></span></a>
									<input type="checkbox" id="drop-2" />
									<ul>
										<li><a href="#best" class="drop-text">Healthy Food</a></li>
										<li><a href="/about_us/" class="drop-text">Farmers</a></li>
										<li><a href="#testi" class="drop-text">Testimonials</a></li>
										<li><a href="#newsletter" class="drop-text">Newsletter</a></li>
									</ul>
								</li>
								<li class="{% block contactpage %}{% endblock %}"><a href="{% url 'themeapp:contact' %}">Contact Us</a></li>
							</ul>
						</nav>
					</div>
					<!-- //nav -->
				</div>
			</div>
		</header>
		<!-- //header -->

		{% block banner %}

		{% endblock %}
		<!-- //banner -->
	</div>
	<!-- //main -->
	{% block body %}

	{% endblock %}





	<!-- about -->
	
	<!-- //slides images -->

	<!-- footer -->
	<footer class="py-5">
		<div class="container pt-xl-5 pt-lg-3">
			<!-- newsletter -->
			<div class="newsletter_right_w3w3pvt-lau pb-md-5 pb-3" id="newsletter">
				<h2 class="tittle text-wh mb-5 font-weight-bold">Subscribe Newsletter</h2>
				<div class="n-right-w3ls pt-3">
					<form action="#" method="post">
						<div class="row">
							<div class="col-md-4 form-group">
								<input class="form-control" type="text" name="Name" placeholder="Name" required="">
							</div>
							<div class="col-md-4 form-group px-md-0">
								<input class="form-control" type="email" name="Email" placeholder="Email Address" required="">
							</div>
							<div class="col-md-4 form-group mt-md-0 mt-3">
								<button class="form-control btn text-uppercase" type="submit">Subscribe</button>
							</div>
						</div>
					</form>
				</div>
			</div>
			<!-- //newsletter -->
			<!-- footer bottom -->
			<div class="row pt-xl-5 pt-lg-3">
				<!-- button -->
				<div class="col-lg-5 col-md-7 w3l-footer mt-lg-3 text-md-left text-center">
					<ul class="list-unstyled footer-nav-wthree">
						<li class="mr-4">
							<a href="index.html" class="active">Home</a>
						</li>
						<li class="mr-4">
							<a class="" href="about.html">About Us</a>
						</li>
						<li class="mr-4">
							<a class="" href="gallery.html">Gallery</a>
						</li>
						<li>
							<a class="" href="contact.html">Contact Us</a>
						</li>
					</ul>
				</div>
				<!-- //button -->
				<!-- social icons -->
				<div class="col-lg-7 col-md-5 w3social-icons text-md-right text-center mt-md-0 mt-3">
					<ul>
						<li>
							<a href="#" class="rounded-circle">
								<i class="fa fa-facebook-f"></i>
							</a>
						</li>
						<li class="px-2">
							<a href="#" class="rounded-circle">
								<i class="fa fa-google-plus"></i>
							</a>
						</li>
						<li>
							<a href="#" class="rounded-circle">
								<i class="fa fa-twitter"></i>
							</a>
						</li>
					</ul>
				</div>
				<!-- //social icons -->
			</div>
			<!-- //footer bottom -->
			<!-- copyright -->
			<div class="row pt-lg-4 pt-3 text-md-left text-center">
				<p class="col-xl-7 col-lg-8 copy-right-grids mt-lg-1">© 2019 Organic Food. All Rights Reserved | Design by
					<a href="https://w3layouts.com/" target="_blank">W3layouts</a>
				</p>
				<div class="col-xl-5 col-lg-4 text-center mt-lg-0 mt-4">
					<a href="#home" class="move-top"></a>
				</div>
			</div>
			<!-- //copyright -->
		</div>
	</footer>
	<!-- //footer -->

</body>

</html>

templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block body %}
{% block contactpage %}active{% endblock %}


section class="contact py-5">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="title-w3 mb-5 font-weight-bold">Contact Us <span>Send Message</span></h3>
			<div class="row">
				<!-- contact form -->
				<div class="col-lg-6 contact-us1-bottom w3layouts-w3ls">
					<form action="#" method="post">
						<div class="form-group">
							<input type="text" class="form-control" placeholder="Name" name="name" required="">
						</div>
						<div class="form-group">
							<input type="email" class="form-control" placeholder="Email" name="email" required="">
						</div>
						<div class="form-group">
							<textarea class="form-control" placeholder="Message" name="message" required=""></textarea>
						</div>
						<button type="submit" class="btn">Submit</button>
					</form>
				</div>
				<!-- //contact form -->
				<!-- contact address -->
				<div class="col-lg-6 home-radio-clock mt-lg-0 mt-5">
					<h3 class="tittle text-dark mb-5 font-weight-bold">Get In Touch</h3>
					<div class="row">
						<div class="col-4">
							<ul class="list-unstyled">
								<li><i class="fa fa-envelope mr-2" aria-hidden="true"></i>Address</li>
								<li class="my-5"><i class="fa fa-phone mr-2" aria-hidden="true"></i>Call Us</li>
								<li><i class="fa fa-clock-o mr-2" aria-hidden="true"></i>Opening Time</li>
							</ul>
						</div>
						<div class="col-8">
							<div class="home-radio-clock-right">
								<ul class="list-unstyled">
									<li>4978 Diamond Circle,
										<span>NJ 07087, USA</span></li>
									<li class="my-4">(012) 123-456-78
										<span>(012) 123-456-78</span>
									</li>
									<li>Mon-Sat:<span>07h-16h</span></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<!-- //contact address -->
			</div>
		</div>
	</section>
	<!-- map -->
	<div class="map">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26359195.17562375!2d-113.7156245614499!3d36.2473834534249!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54eab584e432360b%3A0x1c3bb99243deb742!2sUnited+States!5e0!3m2!1sen!2sin!4v1471497559566"
		 style="border:0" allowfullscreen=""></iframe>
	</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block body %}
<h3>Login</h3>
<p>{{error}}</p>
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button class="btn btn-info">Login</button>
	
</form>

{% endblock %}